- server/db/sql.js
- server/router/userRankRouter.js
> 240228_회원등급sql수정중_장효은

- server/db/sql.js
- server/router/ordersRouter.js
> 240228_주문쿼리문수정_신수지

- server/db/detailreview.js
- server/db/sql.js
- server/router/detailreviewRouter.js
> 240228_리뷰쿼리작업중_박지웅

- client/package-lock.json
- client/package.json
- client/src/router/main.js
- client/src/views/OrderView.vue
- client/vue.config.js
- server/app.js
- server/db/cart.js
- server/db/save.js
- server/db/sql.js
- server/router/cartRouter.js
- server/router/saveRouter.js
> 240229_주문목록작업_신수지

- client/src/layouts/FooterComponent.vue
- client/src/layouts/HeaderComponent.vue
- client/src/layouts/headers/GnbView.vue
- client/src/layouts/headers/NavView.vue
- client/src/layouts/headers/SearchView.vue
240229_메인레이아웃(중간커밋)_장효은 (14:25)
> 240229_메인레이아웃(중간커밋)_장효은

- server/app.js
- server/db/qnas.js
- server/db/qrys.js
- server/db/reviews.js
- server/db/sql.js
- server/router/qnaRouter.js
- server/router/qryRouter.js
240229_qna,문의쿼리문및라우팅진행중 (14:30)
> 240229_qna,문의쿼리문및라우팅진행중

- client/src/layouts/HeaderAdminComponent.vue
- client/src/layouts/SideBarAdminComponent.vue
- client/src/router/admin.js
- client/src/router/main.js
- client/src/views/AdminMainView.vue
- client/src/views/DashBoardView.vue
- client/src/views/OrderView.vue
- server/db/qnas.js
240229_메인,관리자메인수정중_장효은 (29일마감)
> 240229_메인,관리자메인수정중_장효은

- client/package-lock.json
- client/package.json
- client/src/main.js
- client/src/store/index.js
- client/src/views/OrderView.vue
- client/src/views/UserView.vue
- server/db/qnas.js
- server/package-lock.json
- server/package.json
- server/router/userRouter.js
> 240229_로그인화면구현(도승민)

- client/src/views/BookInfoView.vue
- client/src/views/OrderView.vue
- server/db/qnas.js
- server/router/bookRouter.js
> 2.29 도서상세 틀잡음

- client/src/views/OrderView.vue
- server/db/qnas.js
- server/db/userranks.js
- server/router/userRankRouter.js
> 240229_주문결제작업_신수지

- client/src/router/main.js
- client/src/views/MainBookListView.vue
- client/src/views/OrderView.vue
- server/app.js
- server/db/qnas.js
- server/db/qrys.js
240229_메인도서리스트진행중_박지웅 (29일 마감)
> 240229_메인도서리스트진행중_박지웅

- client/src/views/MainBookListView.vue
박지웅 240229h 메인도서목록구현진행 (24.03.01 16:10 merge)
> 박지웅 240229h 메인도서목록구현진행

- client/src/views/BookInfoView.vue
- client/src/views/BookSearchView.vue
- server/app.js
- server/db/books.js
- server/router/bookRouter.js
> 240302_책상세구현중_유민

- client/src/router/main.js
- client/src/views/MenuBookListView.vue
- server/db/books.js
- server/router/bookRouter.js
> 박지웅 도서목록뷰및쿼리문대부분완성 240302

- client/src/router/main.js
- client/src/views/CartView.vue
- client/src/views/OrderView.vue
> 240303_결제API&장바구니_신수지

- client/src/views/NoticeView.vue
- client/src/views/UserListview.vue
> 240304_로그인,회원리스트(도승민)

- client/public/index.html
- client/src/router/main.js
- client/src/views/UserView.vue
- server/app.js
- server/db/user.js
- server/router/userRouter.js
> 240304_로그인_도승민

- client/package-lock.json
- client/package.json
- client/src/layouts/headers/GnbView.vue
- client/src/router/main.js
- client/src/views/UserView.vue
- server/db/user.js
> Hyoeun 0304

- client/src/layouts/headers/GnbView.vue
- client/src/store/index.js
- client/src/views/CartView.vue
- server/db/cart.js
> 240305_장바구니_신수지

- client/src/views/MenuBookListView.vue
- server/db/bookLists.js
- server/router/bookListRouter.js
> 240304h_페이징완성?_박지웅

- client/public/index.html
- client/src/components/NaverLogin.vue
- client/src/components/OpenPostcode.vue
- client/src/layouts/SideBarAdminComponent.vue
- client/src/layouts/headers/GnbView.vue
- client/src/router/admin.js
- client/src/router/index.js
- client/src/router/login.js
- client/src/router/main.js
- client/src/views/NoticeInfoView.vue
- client/src/views/NoticeView.vue
- client/src/views/UserInfoView.vue
- client/src/views/UserInsertView.vue
- client/src/views/UserJoinView.vue
- client/src/views/UserUpdateView.vue
- client/src/views/UserView.vue
- client/vue.config.js
- server/db/user.js
- server/router/userRouter.js
> 240305_회원가입완(로그아웃미완)_도승민

- client/src/App.vue
- client/src/layouts/headers/SearchView.vue
- client/src/views/BookSearchListView.vue
- server/db/books.js
- server/db/sql.js
- server/router/bookRouter.js
> 3.5 검색결과화면 구현 80%, watch공부

- client/src/layouts/headers/NavView.vue
- client/src/router/main.js
- client/src/views/navs/BestSellerListView.vue
- client/src/views/navs/CategoryBookListView.vue
- client/src/views/navs/RecommendListView.vue
- server/db/bookLists.js
- server/router/bookListRouter.js
> 240305_박지웅

- client/src/views/navs/RecommendListView.vue
> 240306_아마도컴포넌트를나누는게필요_박지웅

- client/src/views/CartView.vue
- server/db/cart.js
> 240306_장바구니_신수지

- client/src/views/BookSearchListView.vue
> 240306_중간커밋

- client/src/layouts/headers/NavView.vue
- client/src/router/main.js
- client/src/views/navs/RecommendListMenuView.vue
- client/src/views/navs/RecommendListView.vue
> 240306_추천도서정렬완료

- client/src/store/index.js
- client/src/views/BookInfoView.vue
- server/db/cart.js
- server/router/cartRouter.js
0306_유민_중복체크 이어서하기 (watch 미해결)
> 0306_유민_중복체크 이어서하기

- client/package.json
- client/src/components/OpenPostcode.vue
- client/src/router/main.js
- client/src/views/OrderListView.vue
- client/src/views/OrderView.vue
- server/app.js
- server/db.js
- server/db/cart.js
- server/db/ordersdetail.js
- server/db/sql.js
> 240307_장바구니수정_신수지

- client/package-lock.json
- client/package.json
- client/src/components/NaverLogin.vue
- client/src/layouts/headers/GnbView.vue
- client/src/router/admin.js
- client/src/router/main.js
- client/src/store/index.js
- client/src/views/NoticeFormView.vue
- client/src/views/NoticeInfoView.vue
- client/src/views/NoticeView.vue
- client/src/views/UserInfoView.vue
- client/src/views/UserJoinView.vue
- client/src/views/UserView.vue
- server/db/notice.js
- server/router/noticeRouter.js
> 240307_로그인아웃,공지사항_도승민

- client/package-lock.json
- client/package.json
- client/src/views/BookReviewView.vue
- client/src/views/LikeCntView.vue
- client/src/views/ReviewView.vue
- server/db/reviews.js
- server/router/reviewRouter.js
> 박지웅 240307

- client/src/views/BookReviewView.vue
- client/src/views/LikeCntView.vue
- client/src/views/ReviewView.vue
- server/db/reviews.js
- server/router/reviewRouter.js
> 240307h_다음:정렬이랑페이징라우터합치기_박지웅

- client/src/layouts/SideBarAdminComponent.vue
- client/src/router/admin.js
- client/src/views/FileView.vue
> 240308_관리자페이지해야함_장효은

- client/src/components/NaverLogin.vue
- client/src/router/admin.js
- client/src/views/NoticeFormView.vue
- client/src/views/NoticeInfoView.vue
- client/src/views/NoticeInsertView.vue
- client/src/views/NoticeUpdateView.vue
- client/src/views/NoticeView.vue
- client/src/views/UserInfoView.vue
- client/src/views/UserListview.vue
- client/src/views/UserUpdateView.vue
- client/src/views/UserView.vue
- server/db/notice.js
- server/db/user.js
- server/router/noticeRouter.js
- server/router/userRouter.js
> Doseungmin

- client/package.json
- client/src/layouts/headers/GnbView.vue
- client/src/router/main.js
- client/src/views/BookInfoView.vue
- client/src/views/BookListView.vue
- client/src/views/BookSearchListView.vue
- client/src/views/CartView.vue
- client/src/views/MyOrderListView.vue
- client/src/views/MypageView.vue
- client/src/views/OrderCompleteView.vue
- client/src/views/OrderListView.vue
- client/src/views/ReviewListView.vue
- client/src/views/SaveView.vue
- client/src/views/UserJoinView.vue
- client/src/views/UserView.vue
- client/src/views/navs/BestsellerBookMenuView.vue
- client/src/views/navs/RecommendBookMenuView.vue
- server/db/cart.js
- server/db/ordersdetail.js
- server/db/save.js
- server/router/cartRouter.js
- server/router/ordersdetailRouter.js
- server/router/saveRouter.js
> 240310 sinsuji

- client/src/layouts/headers/SearchView.vue
- client/src/views/BookInfoView.vue
- client/src/views/CartView.vue
- client/src/views/MyOrderListView.vue
- client/src/views/MypageView.vue
- client/src/views/OrderListView.vue
- client/src/views/OrderView.vue
- client/src/views/SaveView.vue
- server/app.js
- server/db/books.js
- server/db/cart.js
- server/db/save.js
- server/router/cartRouter.js
> 240311 sinsuji

- client/src/components/NaverLogin.vue
- client/src/layouts/headers/NavView.vue
- client/src/router/main.js
- client/src/views/MypageView.vue
- client/src/views/SearchId.vue
- client/src/views/UserInfo2View.vue
- client/src/views/UserInfoView.vue
- client/src/views/UserJoinView.vue
- client/src/views/UserListview.vue
- client/src/views/UserUpdateView.vue
- client/src/views/UserView.vue
- server/db/user.js
- server/router/userRouter.js
> 240311_네이버db저장작업중_도승민

- client/src/router/main.js
- client/src/views/BookInfoView.vue
- client/src/views/MyReviewList.vue
- client/src/views/MypageView.vue
- client/src/views/ProductDetailView.vue
- client/src/views/ProductInsertView.vue
- server/db/books.js
- server/db/product.js
> 240311_중간커밋_장효은

- client/src/layouts/headers/NavView.vue
- server/app.js
- server/db/user.js
> 240311_오류수정_2조

- client/src/views/CartView.vue
- client/src/views/MainLiteBannerView.vue
- client/src/views/MyOrderListView.vue
- client/src/views/MyReviewList.vue
- client/src/views/NoticeInfoView.vue
- client/src/views/NoticeView.vue
- client/src/views/OrderListView.vue
- client/src/views/OrderView.vue
- client/src/views/ProductListView.vue
- client/src/views/SalesListView.vue
- client/src/views/UserInfo2View.vue
- client/src/views/navs/CategoryBookMenuView.vue
> 240312_CSS수정_신수지

- client/src/views/MyReviewList.vue
- client/src/views/QnaListView.vue
- client/src/views/RegisterModalView.vue
- client/src/views/ReviewListView.vue
- client/src/views/UpdateQnaView.vue
- server/db/qnas.js
- server/db/reviews.js
- server/router/reviewRouter.js
> 240312_최종_박지웅

- client/src/views/NoticeInfoView.vue
- client/src/views/NoticeInsertView.vue
- client/src/views/NoticeUpdateView.vue
- client/src/views/UserListview.vue
> 240312_수정_도승민

- client/src/views/MyOrderListView.vue
- client/src/views/OrderCompleteView.vue
- server/db/orders.js
> 240312_내주문내역수정_신수지
